# Generated by Django 6.0.3 on 2026-08-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom negotiated price for Enterprise plan. If set, this overrides the default plan price.', max_digits=10, null=True),
        ),
    ]
