# Generated by Django 6.0.3 on 2026-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('shop_admin', 'Shop Admin'), ('inventory_manager', 'Inventory Manager'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
    ]
