# Generated by Django 6.0.3 on 2026-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_barcode_auditlog_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('credit', 'Credit')], default='cash', help_text='Payment method for this specific item (supports split billing)', max_length=20),
        ),
    ]
