# Generated by Django 6.0.3 on 2026-08-31 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_saleitem_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_reason',
            field=models.TextField(blank=True, help_text="Reason for discount (e.g., 'Customer loyalty', 'Bulk order')", null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Amount (KES)'), ('percent', 'Percentage (%)')], help_text='Type of discount applied (fixed amount or percentage)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount (KES) or percentage value', max_digits=12, null=True),
        ),
    ]
