"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'inventory',
    'billing.apps.BillingConfig',
    'alerts.apps.AlertsConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'config.middleware.AdminIPRestrictionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'inventory.middleware.ShopIsolationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url
DATABASES = {
    'default': dj_database_url.config(default=f"sqlite:///{BASE_DIR}/db.sqlite3")
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Allow Railway domains and localhost
ALLOWED_HOSTS = [
    ".railway.app",
    "localhost", 
    "127.0.0.1",
    "::1",
]

CSRF_TRUSTED_ORIGINS = [
    "https://stockhive-backend.up.railway.app",
    "https://stockhive.up.railway.app",
    "https://stockhive.pourexpress.co.ke",
]

CORS_ALLOWED_ORIGINS = [
    "https://stockhive.up.railway.app",
    "http://localhost:5173", # If you do local development
    "https://stockhive.pourexpress.co.ke",
]


CORS_ALLOW_CREDENTIALS = True

MPESA_ENV = os.getenv("MPESA_ENV", "sandbox")
MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY", "")
MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET", "")
MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE", "")
MPESA_PASSKEY = os.getenv("MPESA_PASSKEY", "")
MPESA_CALLBACK_URL = os.getenv(
    "MPESA_CALLBACK_URL",
    "https://stockhive-backend.up.railway.app/api/billing/mpesa/callback/",
)

# Africa's Talking WhatsApp Integration
AT_USERNAME = os.getenv("AT_USERNAME", "")
AT_API_KEY = os.getenv("AT_API_KEY", "")
AT_WHATSAPP_NUMBER = os.getenv("AT_WHATSAPP_NUMBER", "")

# Admin Panel IP Restriction
ADMIN_ALLOWED_IPS = os.getenv("ADMIN_ALLOWED_IPS", "127.0.0.1").split(",")
ADMIN_ALLOWED_IPS = [ip.strip() for ip in ADMIN_ALLOWED_IPS]

# Celery Configuration Options
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_START = True  # Retry connecting to Redis on startup
CELERY_TASK_PUBLISH_RETRY = True  # Retry enqueuing tasks if the broker is momentarily down

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "reconcile-mpesa-payments": {
        "task": "billing.tasks.reconcile_pending_payments",
        "schedule": crontab(minute="*/10"),
    },
    "expire-subscriptions-daily": {
        "task": "billing.tasks.expire_subscriptions_task",
        "schedule": crontab(hour=0, minute=0),
    },
    "log-daily-metrics": {
        "task": "billing.tasks.log_daily_metrics_task",
        "schedule": crontab(hour=1, minute=0),  # Run at 1 AM UTC daily
    },
}

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,  # Ensures app doesn't crash if Redis is down
        }
    }
}


# Use Cache for Sessions (Horizontal Scalability)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Unfold Admin Configuration
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "StočkHive Admin",
    "SITE_HEADER": "StočkHive",
    "SITE_SUBHEADER": "System Owner Panel",
    "SITE_URL": "/",
    "COLORS": {
        "primary": {
            "50":  "255 251 235",
            "100": "254 243 199",
            "200": "253 230 138",
            "300": "252 211 77",
            "400": "251 191 36",
            "500": "245 158 11",   # amber — matches StočkHive brand
            "600": "217 119 6",
            "700": "180 83 9",
            "800": "146 64 14",
            "900": "120 53 15",
            "950": "69 26 3",
        },
    },
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Platform",
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Businesses",
                "items": [
                    {
                        "title": "All Businesses",
                        "icon": "business",
                        "link": reverse_lazy("admin:inventory_business_changelist"),
                    },
                    {
                        "title": "Shops",
                        "icon": "store",
                        "link": reverse_lazy("admin:inventory_shop_changelist"),
                    },
                    {
                        "title": "Users",
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                ],
            },
            {
                "title": "Billing",
                "items": [
                    {
                        "title": "Subscriptions",
                        "icon": "subscriptions",
                        "link": reverse_lazy("admin:billing_subscription_changelist"),
                    },
                    {
                        "title": "M-PESA Payments",
                        "icon": "payments",
                        "link": reverse_lazy("admin:billing_mpesapayment_changelist"),
                    },
                ],
            },
            {
                "title": "Inventory",
                "items": [
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventory_product_changelist"),
                    },
                    {
                        "title": "Sales",
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:inventory_sale_changelist"),
                    },
                ],
            },
        ],
    },
}

STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ─────── BILLING & PAYMENT CONFIGURATION ──────────────────────

# M-Pesa Webhook IP Whitelist (Safaricom IPs)
# Production: 196.201.214.0/24 and 196.201.215.0/24
# Sandbox: 196.201.214.0/24
# For development, add your test server IP
MPESA_ALLOWED_IPS = os.getenv("MPESA_ALLOWED_IPS", "127.0.0.1,::1").split(",")
MPESA_ALLOWED_IPS = [ip.strip() for ip in MPESA_ALLOWED_IPS]

# M-Pesa webhook signature verification (optional, advanced security)
MPESA_SECRET_KEY = os.getenv("MPESA_SECRET_KEY", None)

# ─────── LOGGING CONFIGURATION ──────────────────────────────

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(message)s",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "stockhive.log",
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 10,
            "formatter": "verbose",
        },
        "payment_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "billing_payment.log",
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 20,
            "formatter": "verbose",
        },
        "webhook_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "billing_webhook.log",
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 20,
            "formatter": "verbose",
        },
        "reconciliation_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "billing_reconciliation.log",
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
        },
        "billing.payment": {
            "handlers": ["console", "payment_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "billing.webhook": {
            "handlers": ["console", "webhook_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "billing.reconciliation": {
            "handlers": ["console", "reconciliation_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "billing.security": {
            "handlers": ["console", "webhook_file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# Create logs directory if it doesn't exist
import os as _os
_logs_dir = BASE_DIR / "logs"
_logs_dir.mkdir(exist_ok=True)
