# Generated by Django 6.0.3 on 2026-04-08 06:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('inventory', '0003_alter_stocktransfer_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='alerts_inap_shop_id_50697e_idx',
            old_name='alerts_notif_shop_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='alerts_stoc_product_b77ecd_idx',
            old_name='alerts_stock_product_channel_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='alerts_stoc_shop_id_b3454f_idx',
            old_name='alerts_stock_shop_idx',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='inventory.business'),
        ),
    ]
